sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - cd complex-gcp
  - openssl aes-256-cbc -K $encrypted_c128eb8c1e16_key -iv $encrypted_c128eb8c1e16_iv -in multi-k8s-291320-d802f56b2840.json.enc -out multi-k8s-291320-d802f56b2840.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-291320
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials k8s-multicluster 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t valentynshcherban/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true valentynshcherban/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master