language: generic 

sudo: required 
services:
  - docker

before_install:
  - cd frontend
  - docker build -t valentynshcherban/udemy-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true valentynshcherban/udemy-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-452709507547"
  bucket_path: "docker-react"
  skip_cleanup: true
  on:
    branch: master
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
  cache_control: no-cache
