language: generic 

sudo: required 
services:
  - docker

before_install:
  - cd frontend
  - docker build -t valentynshcherban/udemy-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true valentynshcherban/udemy-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-452709507547"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY" 
  edge: true 
